# Generated by Django 4.2.4 on 2023-08-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('rating', models.DecimalField(decimal_places=0, max_digits=2)),
                ('summary', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
