# Generated by Django 4.2.4 on 2023-08-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_movie_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='date',
            new_name='release_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='YourDefaultDirectorName', max_length=100),
        ),
    ]
