# Generated by Django 4.2.4 on 2023-08-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='_review',
        ),
    ]
