# Generated by Django 4.2.4 on 2023-08-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_review__review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie_name',
            field=models.CharField(default='defaultmoviename', max_length=100),
        ),
    ]
